NLP_WebApplication/HuggingFace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
]

NLP_WebApplication/apps/urls.py
from django.urls import include, path
from . import views

app_name = 'apps'

urlpatterns = [
    path("", views.index, name="index"),
    path('summarization/', views.summarize, name='summarize'),
    path('textgenerator/', views.textgenerator, name='textgenerator'),
    path('questions/', views.qa, name='qa'),
    path('classification/', views.sentimental, name='sentimental'),
    path('translation/', views.translate, name='translate'),
]

NLP_WebApplication/apps/models.py
from django.db import models

# Create your models here.

NLP_WebApplication/apps/views.py
from django.shortcuts import render, redirect
from . import predict
import logging
from django.shortcuts import render
from django.http import HttpResponseServerError
from . import predict

# Create your views here.

logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'apps/index.html')
    
def summarize(request):
    if request.method == "POST":
        text = request.POST.get("abstract")
        conclude = predict.summarizetext(text)[0]['summary_text']
        return render(request, 'apps/summarize.html', {
            "conclude": conclude,
            "abstract": text,
        })
    return render(request,'apps/summarize.html')

def textgenerator(request):
    if request.method == "POST":
        prompt = request.POST.get("prompt")
        length = int(request.POST.get("length"))
        result = predict.generator(prompt, length)[0]['generated_text']
        return render(request, 'apps/generation.html', {
            "result": result,
            "text": prompt,
        })
    return render(request, 'apps/generation.html')

def qa(request):
    if request.method == "POST":
        question = request.POST.get("question")
        context = request.POST.get("context")
        result = predict.QA(context, question)
        return render(request, 'apps/questions.html',{
            "answer": result[0],
            "score": result[1],
            "question": question,
            "context": context,
        })
    return render(request, 'apps/questions.html')

def sentimental(request):
    if request.method == "POST":
        review = request.POST.get("review")
        logger.info(f"Received review: {review}")
        
        try:
            result = predict.classification(review)
            logger.info(f"Model output: {result}")
            
            # Update the mapping dictionary to match your model's labels
            mapping = {
                'anger': 'Anger',
                'disgust': 'Disgust',
                'fear': 'Fear',
                'joy': 'Joy',
                'neutral': 'Neutral',
                'sadness': 'Sadness',
                'surprise': 'Surprise',
                'optimism': 'Optimism'
            }
            
            label = result[0]['label']
            emotion = mapping.get(label, 'Unknown')
            score = result[0]['score']
            
            logger.info(f"Emotion: {emotion}, Score: {score}")
            
            return render(request, 'apps/sentimental.html', {
                "emotion": emotion,
                "score": round(score, 3),
                "review": review,
            })
        except KeyError as e:
            logger.error(f"KeyError: {e} - Label '{label}' not found in mapping.")
            return HttpResponseServerError(f"Label '{label}' not found in mapping.")
        except Exception as e:
            logger.error(f"Unexpected error: {e}")
            return HttpResponseServerError(f"Unexpected error: {e}")
    
    return render(request, 'apps/sentimental.html')


def translate(request):
    if request.method == "POST":
        text = request.POST.get("text")
        result = predict.translation(text)
        return render(request, 'apps/translate.html',{
            "result": result[0]['translation_text'],
            "text": text,
        })
    return render(request, 'apps/translate.html')



NLP_WebApplication/apps/templates/apps/generation.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Text generation</h2>
<div class="container">
    <form action="{% url 'apps:textgenerator' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control jTextarea" id="jTextarea'" rows="5" name="prompt"
                placeholder="Write your text here..." required>{{ text }}</textarea>
        </div>
        Length: <input style="margin-top: 3em" type="number" placeholder="Max length" name="length" max="300"
            value="30">
        <br>
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% if result %}
    Generated text: <textarea class="form-control jTextarea" id="jTextarea'" rows="3">{{ result }}</textarea>
    {% endif %}
</div>
<script>
    $("#001").addClass("active");
</script>
{% endblock %}

NLP_WebApplication/apps/templates/apps/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NLP Django Web Project</title>
    <link rel="stylesheet" href="apps/static/apps/style.css"> <!-- Update with the correct path to your CSS file -->
</head>
<body>
    {% extends "apps/layout.html" %}

    {% block body %}

    <section class="introduction">
        <h1 class="heading" style="color: #3498db;">NLP Django Web Project</h1> <!-- Blue Heading -->
        <p style="color: #000;">Prepared for / Dr. Samia M. Abd-Alhalem</p> <!-- Black text -->
    </section>

    <!-- <section class="developer-info">
        <h1 class="heading" style="color: #3498db;">Developer</h1> 
        <p style="color: #000;">Mahmoud Osama</p> Black text
    </section> 
    -->

    <section class="team-members">
        <h1 class="heading" style="color: #3498db;">Team Members</h1> <!-- Blue Heading -->
        <ul style="color: #000;"> <!-- Black text -->
            <li>Mahmoud Osama 4221021</li>
            <li>Omar Amgad 4221052</li>
            <li>Mahmoud Arafa 4221008</li>
            <li>Maryam Hassan 4221094</li>
            <li>Alaa Yousef 4221366</li>
            <li>Nour El-Din Ayman 4221284</li>
            <li>Monira Ashraf 4221329</li>
            <li>Engy Hossam 4221055</li>
        </ul>
    </section>

    <footer class="content-footer">
        <p class="body-copy" style="color: #ecf0f1;">Say hi to me on these social networks:</p> <!-- Light grey text -->
        <ul class="social">
            <li><a href="https://github.com/fangyiyu" target="_blank" style="color: #3498db;">Github</a></li> <!-- Blue link -->
            <li><a href="https://www.linkedin.com/in/fangyiyu/" target="_blank" style="color: #3498db;">LinkedIn</a></li> <!-- Blue link -->
            <li><a href="mailto:yufangyi1@gmail.com" target="_blank" style="color: #3498db;">Gmail</a></li> <!-- Blue link -->
        </ul>
    </footer>

    {% endblock %}
</body>
</html>

NLP_WebApplication/apps/templates/apps/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} NLP projects {% endblock %}</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'apps/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'apps/starability-all.min.css' %}" />
    <link rel="shortcut icon" href="{% static 'apps/logo.ico' %}" />

    <!-- javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="{% url 'apps:index' %}">NLP Projects</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector">
                    <div class="left"></div>
                    <div class="right"></div>
                </div>
                <li class="nav-item" id="001">
                    <a class="nav-link" href="{% url 'apps:textgenerator' %}">Text Generator</a>
                </li>
                <li class="nav-item" id="003">
                    <a class="nav-link" href="{% url 'apps:summarize' %}">Text Summarization</a>
                </li>
                <li class="nav-item" id="004">
                    <a class="nav-link" href="{% url 'apps:qa' %}">Question Answering</a>
                </li>
                <li class="nav-item" id="005">
                    <a class="nav-link" href="{% url 'apps:sentimental' %}">Sentimental Analysis</a>
                </li>
                <li class="nav-item" id="006">
                    <a class="nav-link" href="{% url 'apps:translate' %}">Machine Translation</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class='wrapper'>
        {% block body %}

        {% endblock %}
    </div>
    <script src="{% static 'apps/custom.js' %}"></script>

</body>

</html>

NLP_WebApplication/apps/templates/apps/questions.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Question Answering</h2>
<div class="container">
    <form action="{% url 'apps:qa' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control jTextarea" id="jTextarea'" rows="5" name="context"
                placeholder="Write your context here..." required></textarea>
            <br>
            <textarea class="form-control jTextarea" id="jTextarea'" rows="1" name="question"
                placeholder="Write your question here..." required>{{ questtion }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
</div>
</form>
{% if answer %}
Answer: <textarea class="form-control jTextarea" id="jTextarea'" rows="1">{{ answer }}</textarea>
<span><small>with confidence {{ score }}</small></span>
{% endif %}
<script>
    $("#004").addClass("active");
</script>

{% endblock %}

NLP_WebApplication/apps/templates/apps/sentimental.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Product Review Analysis</h2>
<div class="container">
    <br>
    <span>This is a roBERTa-base model trained on ~58M tweets and finetuned for emotion recognition.
        <br> The emotions are: Joy&#128516; Optimism&#128512; Sadness&#128532; and Anger&#128545;
    </span>
    <form action="{% url 'apps:sentimental' %}" method="POST">
        {% csrf_token %}
        <div class="form-group mt-3">
            <textarea class="form-control jTextarea" id="jTextarea'" rows="5" name="review"
                placeholder="Write your review here..." required>{{ review }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% if emotion %}
    <span><b>Analysis result: </b></span>
    <div style="text-align: center;">{{ emotion }}</div>
    {% endif %}
</div>
<script>
    $("#005").addClass("active");
</script>
{% endblock %}

NLP_WebApplication/apps/templates/apps/summarize.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Text Summarization</h2>
<div class="container">
    <form action="{% url 'apps:summarize' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <textarea maxlength="512" class="form-control jTextarea" id="jTextarea'" rows="3" name="abstract"
                placeholder="Write your text here..." required>{{ abstract }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
</div>
</form>
{% if conclude %}
Abstract: <textarea class="form-control jTextarea" id="jTextarea'" rows="1">{{ conclude }}</textarea>
{% endif %}
<script>
    $("#003").addClass("active");
</script>
{% endblock %}

NLP_WebApplication/apps/templates/apps/translate.html
{% extends "apps/layout.html" %}

{% block body %}

<h2 style="text-align:center; margin-top: 100px;">Machine Translation</h2>
<div class="container">
    <br><br>
    <span>A tool to translate English to French.</span>
    <form action="{% url 'apps:translate' %}" method="POST">
        {% csrf_token %}
        <div class="form-group mt-3">
            <textarea maxlength="215" class="form-control jTextarea" id="jTextarea'" rows="5" name="text"
                placeholder="Write your text here..." required>{{ text }}</textarea>
        </div>
        <button class="btn btn-warning" type="submit">Submit</button>
    </form>
    {% if result %}
    Translated text in French: <textarea class="form-control jTextarea" id="jTextarea'" rows="3">{{ result }}</textarea>
    {% endif %}

</div>
<script>
    $("#006").addClass("active");
</script>
{% endblock %}